package quicmq

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"time"
)

// GenerateTLSConfig creates a self-signed TLS server configuration suitable
// for development and testing. The generated certificate uses P-256 ECDSA
// and is valid for 24 hours.
//
// The "quicmq" ALPN protocol is set automatically.
//
// For production deployments, use NewTLSConfig to load certificates from
// files, or supply your own *tls.Config via the WithListenTLS option.
func GenerateTLSConfig() *tls.Config {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		panic("quicmq: failed to generate ECDSA key: " + err.Error())
	}

	template := x509.Certificate{
		SerialNumber: big.NewInt(1),
		NotBefore:    time.Now(),
		NotAfter:     time.Now().Add(24 * time.Hour),
	}
	pubKey := key.Public()
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, pubKey, key)
	if err != nil {
		panic("quicmq: failed to create certificate: " + err.Error())
	}

	return &tls.Config{
		Certificates: []tls.Certificate{{
			Certificate: [][]byte{certDER},
			PrivateKey:  key,
		}},
		NextProtos: []string{QUICProtocol},
	}
}

// InsecureClientTLSConfig returns a TLS client configuration that skips
// server certificate verification. This is convenient for development and
// testing against self-signed certificates generated by GenerateTLSConfig.
//
// A session cache is included so that 0-RTT session resumption works when
// the same config object is reused across reconnects.
//
// WARNING: Do not use in production. Skipping verification makes the
// connection vulnerable to man-in-the-middle attacks.
func InsecureClientTLSConfig() *tls.Config {
	return &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{QUICProtocol},
		ClientSessionCache: tls.NewLRUClientSessionCache(128),
	}
}

// NewTLSConfig creates a TLS server configuration from PEM-encoded certificate
// and private key files. This is the recommended approach for production
// deployments.
//
// The "quicmq" ALPN protocol is set automatically.
//
// Example:
//
//	tlsCfg, err := quicmq.NewTLSConfig("server.crt", "server.key")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	pub := quicmq.NewPub(ctx, quicmq.WithListenTLS(tlsCfg))
func NewTLSConfig(certFile, keyFile string) (*tls.Config, error) {
	certPEM, err := os.ReadFile(certFile)
	if err != nil {
		return nil, fmt.Errorf("quicmq: read cert file: %w", err)
	}
	keyPEM, err := os.ReadFile(keyFile)
	if err != nil {
		return nil, fmt.Errorf("quicmq: read key file: %w", err)
	}

	cert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return nil, fmt.Errorf("quicmq: parse key pair: %w", err)
	}

	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		NextProtos:   []string{QUICProtocol},
	}, nil
}

// NewClientTLSConfig creates a TLS client configuration with a custom
// certificate authority (CA) for verifying the server's certificate.
//
// caFile should be a PEM-encoded CA certificate file. Pass an empty string
// to use the system's default CA pool.
func NewClientTLSConfig(caFile string) (*tls.Config, error) {
	var pool *x509.CertPool

	if caFile != "" {
		caPEM, err := os.ReadFile(caFile)
		if err != nil {
			return nil, fmt.Errorf("quicmq: read CA file: %w", err)
		}

		pool = x509.NewCertPool()
		if !pool.AppendCertsFromPEM(caPEM) {
			return nil, fmt.Errorf("quicmq: failed to parse CA certificate from %q", caFile)
		}
	}

	return &tls.Config{
		RootCAs:            pool,
		NextProtos:         []string{QUICProtocol},
		ClientSessionCache: tls.NewLRUClientSessionCache(128),
	}, nil
}

// QUICProtocol is the ALPN protocol identifier used by quicmq during the
// TLS handshake. Both client and server must agree on this value.
const QUICProtocol = "quicmq"

// mustParsePEM is a helper that decodes the first PEM block from data.
func mustParsePEM(data []byte) []byte {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil
	}
	return block.Bytes
}
